### PR TITLE
Expire comments by virtual packages

### PR DESCRIPTION
**Pull request by staabm**
### Virtual packages

Within the PHPStan config file you can define additional packages, to match against package-version-todo-comments.

```neon
parameters:
    todo_by:
        virtualPackages:
            'staabm/mypackage': '2.1.0'
            'staabm/my-api': '3.1.0'
```

Reference these virtual packages like any other package in your todo-comments:

`// TODO staabm/mypackage:2.2.0 remove the following function once staabm/mypackage is updated to 2.2.0`

closes https://github.com/staabm/phpstan-todo-by/issues/42

### CODE REVIEW

**Comment by staabm** [comment]
@glaubinix please give it a try

//cc @seldaek

**Comment by Seldaek** [comment]
Looks good to me :) We'll try this after the Xmas season tho

**Comment by staabm** [comment]
Sure thing, no hurry. Have a few great days with the family

**Comment by glaubinix** [comment]
I just gave this a try. Looks great and works as expected! Thank you for getting this done so quick!

**Comment by staabm** [comment]
thanks for the feedback. will be released shortly

**Comment by staabm** [comment]
here we go: https://github.com/staabm/phpstan-todo-by/releases/tag/0.1.18

**Pull request merged**
